version: 0.2

phases:
  install:
    commands:
      - npm install yarn -g
      - yarn install
  pre_build:
    commands:
      - export message_value="$CODEBUILD_RESOLVED_SOURCE_VERSION succeeded"
      - yarn mocha
  build:
    commands:
      - zip -9r index.zip .
  post_build:
    commands:
      - sh deploy.sh